### ISSUE TITLE
why always show Kernel extension load failed ?

### ISSUE THREAD

**Issue by husangen** [FinalTheory/WirelessNetworkReproduction#1]
my system is  macos 10.12.3   ,
and under Recovery mode   Run " csrutil  disable", then Reboot 

but it still show Kernel extension load failed

**Comment by FinalTheory** [comment]
Now there are some compatibility issues on 10.12.3, and things could not work even if kernel extension is correctly loaded.
Sorry for this inconvenience, for simple emulation cases, you could use "Network Link Conditioner" provided by osx itself.
I'll try to fix this later when have time.
