### ISSUE TITLE
Failed on Mac OSX 10.12.

### ISSUE THREAD

**Issue by tilau** [FinalTheory/WirelessNetworkReproduction#2]
Hey due,
We have tried this app on OSX 10.12, but it could not work.
Followed by "Bandwidth Limitation" example, "wget" has not been affected and run with normal status.
What's more, when click "stop" button it will become a deadlock status.

**Comment by FinalTheory** [comment]
Now there are some compatibility issues on 10.12.3, and things could not work even if kernel extension is correctly loaded.
Sorry for this inconvenience, for simple emulation cases, you could use "Network Link Conditioner" provided by osx itself.
I'll try to fix this later when have time.

**Comment by NormanOu** [comment]
So sad about this, I was excited to find this project, but i does not work on 10.12 any nore~
